version: 2
jobs:
  minitest:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          RAILS_ENV: test
          TESTOPTS: "--ci-report --ci-dir=/tmp/test_reports/minitest"
          # https://discuss.circleci.com/t/rails-app-cant-connect-to-postgres-server/13059
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:10.3
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: volunteer_test
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-ruby-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-ruby-dependencies-
      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-ruby-dependencies-{{ checksum "Gemfile.lock" }}
      - run: bundle exec rake db:create db:schema:load
      - run:
          name: run unit tests
          command: bundle exec rake test
      - store_test_results:
          path: /tmp/test_reports

  jest:
    docker:
      - image: circleci/node:8-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-js-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-js-dependencies-
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-js-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: run javascript tests
          command: npm test -- --ci --runInBand --reporters=default --reporters=jest-junit
      - store_test_results:
          path: /tmp/test_reports

workflows:
  version: 2
  test_suite:
    jobs:
      - minitest
      - jest
